title: Progl.ai
description: 
google_analytics: 
show_downloads: true
remote_theme: Grayscale

gems:
  - jekyll-mentions

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
