title: Progressive Learning
description: 
google_analytics: 
show_downloads: false
theme: jekyll-theme-midnight

gems:
  - jekyll-mentions

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
